# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


# Trajectory controller
trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.05
  shoulder_pan_joint: {trajectory: 0.1, goal: 0.001}
  shoulder_lift_joint: {trajectory: 0.1, goal: 0.001}
  elbow_joint: {trajectory: 0.1, goal: 0.001}
  wrist_1_joint: {trajectory: 0.1, goal: 0.001}
  wrist_2_joint: {trajectory: 0.1, goal: 0.001}
  wrist_3_joint: {trajectory: 0.1, goal: 0.001}
  stop_trajectory_duration: 1.0
  state_publish_rate: 25
  action_monitor_rate: 30
  gains:
    # shoulder_pan_joint: {p: 100.0, i: 1.0, d: 1.0}
    # shoulder_lift_joint: {p: 100.0, i: 1.0, d: 1.0}
    # elbow_joint: {p: 100.0, i: 1.0, d: 1.0}
    # wrist_1_joint: {p: 100.0, i: 1.0, d: 1.0}
    # wrist_2_joint: {p: 100.0, i: 1.0, d: 1.0}
    # wrist_3_joint: {p: 100.0, i: 1.0, d: 1.0}
    shoulder_pan_joint: {p: 50.0, i: 0.5, d: 0.5}
    shoulder_lift_joint: {p: 50.0, i: 0.5, d: 0.5}
    elbow_joint: {p: 50.0, i: 0.5, d: 0.5}
    wrist_1_joint: {p: 50.0, i: 0.5, d: 0.5}
    wrist_2_joint: {p: 50.0, i: 0.5, d: 0.5}
    wrist_3_joint: {p: 50.0, i: 0.5, d: 0.5}
# controller_list:
#   - name: "trajectory_controller"
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
