## generate_place_cabinet config
# these are door dims, cabinet dims will be created according to the doors
cabinet_dims: 
  width: 0.3
  height: 0.4
  depth: 0.35
cabinet_pose:
  min_x: 0
  max_x: 0
  min_y: 0.45
  max_y: 0.65
  rot_angle_min_deg: -5
  rot_angle_max_deg: 5

cabinet_urdf_save_path: "/home/RVLuser/ferit_ur5_ws/cabinet.urdf"


## Feasible poses setup
feasible_poses:
  dd_state_deg: 12.0
  num_viewpoints: 100
  num_rot_angles: 12
  load_valid_contact_poses_from_file: False
  load_feasible_poses_from_file: False
  gripper_params:
    is_default_gripper: False
    custom_gripper_spheres_path: '/home/RVLuser/rvl-linux/python/DDMan/3finger_gripper/gripper_spheres.npy'
    custom_gripper_model_path: '/home/RVLuser/rvl-linux/python/DDMan/3finger_gripper/robotiq_3f_gripper_simplified.stl'
    tool_contact_surface_params: [[0.0, -0.026, 0.0], [0.0, -0.031, -0.025]]
    tool_finger_distances: [-0.0775, 0., -0.102]
    sphere_to_TCS_distance: 0.004609
  feasible_poses_path: "/home/RVLuser/rvl-linux/python/DDMan/feasible_poses_3f_gripper.npy"
  valid_contact_poses_path: "/home/RVLuser/rvl-linux/python/DDMan/valid_contact_poses.npy"
  visualization: True

